<!-- <style>
table.ov tbody tr td {
    font-size: 50px;
    text-align: center;
    padding: 15px;
}

table.ns tbody tr td {
    padding: 8px 8px;
}

td.running {
    text-align: center;
    font-size: 20px;
    color: green;
}

span.qt {
    font-size: 14px;
}

span.ago {
    color: #AAAAAA;
}

p.ct {
    padding: 10px 0 5px 0;
}
</style> -->

<style>

.slidediv{
height:350px;
background-color:whitesmoke;}

.margin50{
margin:50px;}

</style>

<!-- <div id="main" class="row" style="margin-left:0px">   
    <div class="well" style="padding:50px 10px;">
        <a href="host.php" class="btn btn-large" style="margin-left:35px"><strong><?php echo $host_count;?></strong> Hosts</a> 
        <a href="service.php" class="btn btn-large"><strong><?php echo $service_count;?></strong> Services</a>
        <a href="service.php" class="btn btn-large"><strong><?php echo $on_service_count;?></strong> Running Services</a>
        <a href="instance.php" class="btn btn-large"><strong><?php echo $instance_count;?></strong> Instances</a>
        <a href="instance.php" class="btn btn-large"><strong><?php echo $running_instance_count;?></strong> Running Instances</a>
    </div>
</div> -->

    <!--  <ul class="breadcrumb">
    <li><a href="index.php">Home</a><span class="divider">/</span></li>
	<li class="active">Host</li>
	</ul> -->
    <h3>Welcome to Search Cloud</h3>
    <br/>      
    <div id="myCarousel" class="carousel slidediv">
        <div class="carousel-inner">
	    <div class="row item active margin50">
		<div class="span10 offset1">
	    <h2>Solr Cloud to Search Cloud</h2>
		<p>从 Solr Cloud 到 Search Cloud，不仅仅是名字的改变</p>
		<p>定位、理念、设计 全新蜕变</p>
		</div>
	    </div>
	    <div class="row item margin50">
	        <div class="span10 offset1">
	        <h3 >简单易容</h3>
		<p>使用门槛更低，search cloud robot尽可能帮你处理掉你可能遗忘的事情</p>
		<p>从此使用无忧</p>
		</div>
	    </div>
	    <div class="row item margin50">
	        <div class="span10 offset1">
	        <h3>we are getting better and better</h3>
		<p>全新起点 将来会更好</p>
		</div>
	    </div>
	</div>
	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
    
    <div class='row-fluid'>
        <div class="span4">
	  <h4>全面支持 Solr 4.0</h4>
	  <p>全面支持 Solr 4.0，新特性包括分布式索引、负载均衡和故障自动迁移、原子更新、事务机制、等等，非常多惊人级别的更新，快来把原来的service升级到4.0吧</p>
	</div>
	<div class="span4">
	  <h4>全新设计</h4>
	  <p>重新定义了产品定位 重新梳理了操作流程 重新组织了信息构架 使用更简单 操作更省心 找到自己想要的信息更快速 一切为了你的使用体验</p>
	</div>
	<div class="span4">
	  <h4>报表增强</h4>
	  <p>新增instance的各种报表，不光只是从service级别，也深入到instance级别，还有各种报警订阅，方便随时接收异常情况 第一时间紧急处理</p>
	</div>
    </div>
    <br />

<!-- <div id="box">
    <h3>Nginx Status</h3>
    <table class="ns">
        <thead>
            <tr>
                <th width="33%">Status</th>
                <th width="34%">Last Reloaded</th>
                <th width="33%">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="running">Running</td>
                <td class="a-center"><span class="qt"><?=$last_nginx_reload['queue_time']?></span><br/>
                    <span class="ago">about <?=$ago?> days ago</span></td>
                <td class="a-center"><a href="service.php?action=reload&service_id=0"><img src="img/icons/restart.gif" /></a></td>
            </tr>
        </tbody>
    </table>
</div> -->
